# Generated by Django 5.1.3 on 2024-12-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={},
        ),
    ]
